In [1]:
import tensorflow as tf
import numpy as np

# Tensor


In [2]:
rand_array = np.random.rand(3, 3)
s = tf.constant('hello CloudMile', dtype=tf.string)
n = tf.constant(rand_array, dtype=tf.float32)
x = tf.placeholder(tf.float32, shape=(3, 3))
y = tf.matmul(x, x)
y_ = tf.Variable(rand_array, trainable=False)
print(rand_array)
print(s)
print(n)
print(x)
print(y)
print(y_)

[[ 0.06110759  0.0848017   0.1856363 ]
 [ 0.98964615  0.63216708  0.27145611]
 [ 0.90406534  0.58269641  0.09500077]]
Tensor("Const:0", shape=(), dtype=string)
Tensor("Const_1:0", shape=(3, 3), dtype=float32)
Tensor("Placeholder:0", shape=(3, 3), dtype=float32)
Tensor("MatMul:0", shape=(3, 3), dtype=float32)
<tf.Variable 'Variable:0' shape=(3, 3) dtype=float64_ref>


# Session

In [3]:
with tf.Session() as sess:
    print(sess.run(s))

b'hello CloudMile'


In [4]:
sess = tf.InteractiveSession()
print(s.eval())
sess.close()

b'hello CloudMile'


# Placeholder

In [5]:
with tf.Session() as sess:
    # ERROR: will fail because x was not fed.
#     print(sess.run(y))     
    # Will succeed.
    print(sess.run(y, feed_dict={x: rand_array}))  

[[ 0.25548515  0.16696048  0.05199932]
 [ 0.93151069  0.64173543  0.3811084 ]
 [ 0.71779537  0.50038439  0.33502901]]


# Variable

In [6]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(y_)) 

[[ 0.06110759  0.0848017   0.1856363 ]
 [ 0.98964615  0.63216708  0.27145611]
 [ 0.90406534  0.58269641  0.09500077]]


In [7]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(s))
    print(sess.run(n))
    print(sess.run(y, feed_dict={x: rand_array})) 
    print(sess.run(y_))


b'hello CloudMile'
[[ 0.06110759  0.0848017   0.1856363 ]
 [ 0.98964614  0.6321671   0.27145612]
 [ 0.90406537  0.58269638  0.09500077]]
[[ 0.25548515  0.16696048  0.05199932]
 [ 0.93151069  0.64173543  0.3811084 ]
 [ 0.71779537  0.50038439  0.33502901]]
[[ 0.06110759  0.0848017   0.1856363 ]
 [ 0.98964615  0.63216708  0.27145611]
 [ 0.90406534  0.58269641  0.09500077]]
